Install script now puts sourceable bash and zsh files in the repository, and adds symlinks from the home directory. Makes it easier to sync this repository across servers. Also changed completion script to allow for natural non-recursive tab completion, suitable for replacing builtin shell completion entirely.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
-
 set -u
-
+[ ${PWD##*/} != .fzf ] && \
+  echo "Error: This directory must be named '.fzf'." && exit 1
 version=0.17.4
 auto_completion=
 key_bindings=
@@ -9,8 +9,13 @@ update_config=2
 binary_arch=
 allow_legacy=
 shells="bash zsh fish"
-prefix='~/.fzf'
-prefix_expand=~/.fzf
+prefix='$HOME/.fzf/.fzf'
+base='$HOME/.fzf'      # will use environment variables
+base_expand=$HOME/.fzf # expanded
+prefix_expand=$HOME/.fzf/.fzf # destination is this directory
+prefix_target=$HOME/.fzf      # prefix for target name
+prefix_source=.fzf/.fzf       # prefix for symlink target; will place in prefix_target
+fish_source=../../.fzf        # loction for symlink in $HOME/.config/fish to point
 fish_dir=${XDG_CONFIG_HOME:-$HOME/.config}/fish
 
 help() {
@@ -73,7 +78,6 @@ for opt in "$@"; do
 done
 
 cd "$(dirname "${BASH_SOURCE[0]}")"
-fzf_base="$(pwd)"
 
 ask() {
   while true; do
@@ -90,7 +94,7 @@ ask() {
 check_binary() {
   echo -n "  - Checking fzf executable ... "
   local output
-  output=$("$fzf_base"/bin/fzf --version 2>&1 | awk '{print $1}')
+  output=$("$base_expand"/bin/fzf --version 2>&1 | awk '{print $1}')
   if [ $? -ne 0 ]; then
     echo "Error: $output"
     binary_error="Invalid binary"
@@ -102,7 +106,7 @@ check_binary() {
     binary_error=""
     return 0
   fi
-  rm -f "$fzf_base"/bin/fzf
+  rm -f "$base_expand"/bin/fzf
   return 1
 }
 
@@ -110,7 +114,7 @@ link_fzf_in_path() {
   if which_fzf="$(command -v fzf)"; then
     echo "  - Found in \$PATH"
     echo "  - Creating symlink: $which_fzf -> bin/fzf"
-    (cd "$fzf_base"/bin && rm -f fzf && ln -sf "$which_fzf" fzf)
+    (cd "$base_expand"/bin && rm -f fzf && ln -sf "$which_fzf" fzf)
     check_binary && return
   fi
   return 1
@@ -139,13 +143,13 @@ try_wget() {
 download() {
   echo "Downloading bin/fzf ..."
   if [[ ! "$version" =~ alpha ]]; then
-    if [ -x "$fzf_base"/bin/fzf ]; then
+    if [ -x "$base_expand"/bin/fzf ]; then
       echo "  - Already exists"
       check_binary && return
     fi
     link_fzf_in_path && return
   fi
-  mkdir -p "$fzf_base"/bin && cd "$fzf_base"/bin
+  mkdir -p "$base_expand"/bin && cd "$base_expand"/bin
   if [ $? -ne 0 ]; then
     binary_error="Failed to create bin directory"
     return
@@ -195,7 +199,7 @@ case "$archi" in
   *)             binary_available=0 binary_error=1 ;;
 esac
 
-cd "$fzf_base"
+cd "$base_expand"
 if [ -n "$binary_error" ]; then
   if [ $binary_available -eq 0 ]; then
     echo "No prebuilt binary for $archi ..."
@@ -210,7 +214,7 @@ if [ -n "$binary_error" ]; then
     fi
     if go get -u github.com/junegunn/fzf; then
       echo "OK"
-      cp "$GOPATH/bin/fzf" "$fzf_base/bin/"
+      cp "$GOPATH/bin/fzf" "$base_expand/bin/"
     else
       echo "Failed to build binary. Installation failed."
       exit 1
@@ -252,12 +256,12 @@ for shell in $shells; do
   src=${prefix_expand}.${shell}
   echo -n "Generate $src ... "
 
-  fzf_completion="[[ \$- == *i* ]] && source \"$fzf_base/shell/completion.${shell}\" 2> /dev/null"
+  fzf_completion="[[ \$- == *i* ]] && source \"$base/shell/completion.${shell}\" 2> /dev/null"
   if [ $auto_completion -eq 0 ]; then
     fzf_completion="# $fzf_completion"
   fi
 
-  fzf_key_bindings="source \"$fzf_base/shell/key-bindings.${shell}\""
+  fzf_key_bindings="source \"$base/shell/key-bindings.${shell}\""
   if [ $key_bindings -eq 0 ]; then
     fzf_key_bindings="# $fzf_key_bindings"
   fi
@@ -265,8 +269,8 @@ for shell in $shells; do
   cat > "$src" << EOF
 # Setup fzf
 # ---------
-if [[ ! "\$PATH" == *$fzf_base/bin* ]]; then
-  export PATH="\$PATH:$fzf_base/bin"
+if [[ ! "\$PATH" == *"$base/bin"* ]]; then
+  export PATH="\$PATH:$base/bin"
 fi
 
 # Auto-completion
@@ -278,15 +282,17 @@ $fzf_completion
 $fzf_key_bindings
 
 EOF
+  ln -sf ${prefix_source}.${shell} ${prefix_target}.${shell}
   echo "OK"
 done
 
 # fish
+# this shell can just read a functions file, no sourcing necessary
 if [[ "$shells" =~ fish ]]; then
   echo -n "Update fish_user_paths ... "
   fish << EOF
-  echo \$fish_user_paths | \grep $fzf_base/bin > /dev/null
-  or set --universal fish_user_paths \$fish_user_paths $fzf_base/bin
+  echo \$fish_user_paths | \grep $base/bin > /dev/null
+  or set --universal fish_user_paths \$fish_user_paths $base/bin
 EOF
   [ $? -eq 0 ] && echo "OK" || echo "Failed"
 
@@ -299,7 +305,7 @@ EOF
   fish_binding="${fish_dir}/functions/fzf_key_bindings.fish"
   if [ $key_bindings -ne 0 ]; then
     echo -n "Symlink $fish_binding ... "
-    ln -sf "$fzf_base/shell/key-bindings.fish" \
+    ln -sf "$fish_source/shell/key-bindings.fish" \
            "$fish_binding" && echo "OK" || echo "Failed"
   else
     echo -n "Removing $fish_binding ... "
@@ -387,3 +393,5 @@ if [ $update_config -eq 1 ]; then
   echo
 fi
 echo 'For more information, see: https://github.com/junegunn/fzf'
+
+
